### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by Chen-WeiZhen** [zhaofinger/finger-blog#1]
![image](https://user-images.githubusercontent.com/18025841/38653801-02d7f870-3e3f-11e8-89c0-48935954a55d.png)
请问这？？？是什么意思呢，占位符吗？刚入门node+mysql，这写法没见过

**Comment by zhaofinger** [comment]
用的是这个[mysql](https://github.com/mysqljs/mysql)库，详细使用可查看文档。
